version: 0.2
env:
  git-credential-helper: yes
  shell: bash
run-as: root
phases:
  pre_build:
    commands:
      - FILES=$(git diff --name-only HEAD^)
      - EXECUTE_ALL_PIPELINE=false
      - EXECUTE_BUILDSPEC=false
      - worker_data="project_a:false#project_b:false"
      - sudo chmod 777 get_worker_status.sh
      - sudo chmod 777 update_worker_status.sh

  build:
    commands:
      - |
        for FILE in ${FILES}; do
          echo $FILE
          worker_data=$(bash update_worker_status.sh $worker_data $FILE)  
        done

  post_build:
    commands:
      - echo ${worker_data}
      - |
        status=($(echo $worker_data | tr ":#" "\n"))
        for ( i=0; i<${#status[@]}; i+=2 ); do
          if [[ ${status[i+1]} = "true" ]]; then
            pipeline_name=data-ai-apne2-ultron-${status[i]//_/-}-pipeline-stg
            echo ${pipeline_name}
            aws codepipeline start-pipeline-execution --name test_project_a --source-revisions actionName=Source,revisionType=COMMIT_ID,revisionValue=${CODEBUILD_RESOLVED_SOURCE_VERSION}
          fi
        done
