version: 0.2
env:
  git-credential-helper: yes
  shell: bash
run-as: root
phases:
  pre_build:
    commands:
      - FILES=$(git diff --name-only HEAD^)
      - EXECUTE_ALL_PIPELINE=false
      - EXECUTE_PROJECT_A=false
      - EXECUTE_PROJECT_B=false
      - EXECUTE_WORKER=false
      - EXECUTE_BUILDSPEC=false
      - declare -A example_array=(["key1"]="value1" ["key2"]="value2" ["key3"]="value3")
      - echo ${#example_array[@]}
      - my_array=("first" "second" "third" "fourth"); for item in "${my_array[@]}"; do echo "$item" ; done
      - |
        for item in ${my_array[@]}; do
          echo $item
        done
      - example_array=(["key1"]="value1", ["key2"]="value2", ["key3"]="value3"); for item in "${!example_array[@]}"; do echo $item; echo $example_array[$item]; done
  build:
    commands:
      - |      
        for key in ${!example_array[@]}; do
            echo $key
        done
      - |          
        for FILE in ${FILES}; do
          echo $FILE
          if [[ $FILE = *ultron/workers/* ]]; then
            EXECUTE_WORKER=true
          elif [[ $FILE = *ultron/libs/* ]] || [[ $FILE = *project-a/__init__.py* ]]; then
            EXECUTE_ALL_PIPELINE=true
          fi
        done

  post_build:
    commands:
      - echo ${EXECUTE_ALL_PIPELINE}
      - echo ${EXECUTE_PROJECT_A}
      - echo ${EXECUTE_PROJECT_B}
      - echo "code source revision id"
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - "
      
        \ if [[ $EXECUTE_ALL_PIPELINE = true ]]; then
        
        \   echo execute all pipeline\
        
        \ else\
        
        \   if [[ $EXECUTE_WORKER = true ]]; then
        
        \     echo execute worker\
        
        \   elif [[ $EXECUTE_BUILDSPEC = true ]]; then
        
        \     echo execute buildspec\
        
        \   fi\
        
        \ fi\
      "
      - 1234
